apiVersion: v1
kind: Pod
metadata:
  name: mc1
spec:
  containers:
    - name: nginx-a
      image: nginx
      ports:
        - containerPort: 80
    - name: nginx-b
      image: nginx
      ports:
        - containerPort: 80 #Nemelo by fungovat - zmenit port
