#!/bin/sh

DOCKER_RUN_OPTIONS="-i --rm"
# Only allocate tty if we detect one
if [ -t 0 ] && [ -t 1 ]; then
    DOCKER_RUN_OPTIONS="$DOCKER_RUN_OPTIONS -t"
fi

docker run \
  $DOCKER_RUN_OPTIONS -w /app \
  -v /home/$(whoami)/.kube:/root/.kube \
  -v $PWD:/app hashicorp/terraform:1.0.11 $@
